version: "3"

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - "DB_HOST"
      - "DB_PORT"
      - "DB_USERNAME"
      - "DB_PASSWORD"
      - "DB_SCHEMA"
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_SCHEMA}"
